version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ab12
      - POSTGRES_DB=movies
    ports:
      - '5432:5432'
